### ISSUE TITLE
Canvas drawImage from local file is not working on Android

### ISSUE THREAD

**Issue by alphasp** [iddan/react-native-canvas#40]
Following code work on iOS but not on Android.
```
  handleCanvas = canvas => {
    const context = canvas.getContext('2d');
    const image = new CanvasImage(canvas);
    const filePath = '/path/to/image.jpg';
    image.src = Platform.OS === 'android' ? `file://${filePath}` : filePath;
    image.addEventListener('load', () => {
      context.drawImage(image, 0, 0, 200, 200);
    });
  };

```

**Comment by iddan** [comment]
This is a problem with RN's WebView component which is out of the scope of this library

**Comment by mauriciomassaia** [comment]
@alphasp I had the same issue so I added to the `baseUrl: ''` to the WebView source and it worked.
I created a fork which is working for me on Android.

https://github.com/mauriciomassaia/react-native-canvas/

@iddan i didnt make a PR because i couldnt make it build properly. I was having issues with the object spread on `build-html.js` so I re-wrote it to copy the object properties.

Cheers

**Comment by xavicolomer** [comment]
I modified line 231 from the dist/Canvas folder:

source: { html: _indexHtml2.default, baseUrl: '' },

But still not working... Any suggestion @mauriciomassaia ?

**Comment by iddan** [comment]
We had a lot of issues with `baseUrl`. @mauriciomassaia have you tested it on the supported native platforms? build-html works on the latest LTS node.
