### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by ggunti** [iddan/react-native-canvas#74]
I converted the `Reacteroids` react application (which is using canvas) into a React Native one. I used this library to have access to Canvas, but it is too slow. It have a very low framerate, it is laggy. What could be the problem? It can be optimized?
The React version is here (it is working well): https://github.com/chriz001/Reacteroids

**Comment by iddan** [comment]
It is slow because all the operations are done through the postMessage API of `<WebView />`. You can speed it up by avoiding `await`-ing for instructions when possible. But this solution is not suitable for gaming in it's current form. I was hoping to convert to a more responsive solution that will emulate a canvas on the React Native side and won't use a WebView but I couldn't find a good canvas implementation: if you know of a C, C++, Rust or JavaScript Canvas API implementation I'd love to integrate it but currently this is the best I can offer.

**Comment by ggunti** [comment]
I understand. Thank you for your response.
